# NUMPY

## VERSION CHECK

In [1]:
import numpy as np
np.__version__

'1.26.4'

## NUMPY ARRAY

In [ ]:
a = np.array([1,2,3,4,'ajeeth'])
a

In [ ]:
type(a)

In [ ]:
a = np.array('data science')
b = np.array(['data science','data analysis','data engineer'])
c = np.array([[1,2,3]])
d = np.array([[[1,2,3,4,5]]])

In [ ]:
print(f'Dimension of a :{a.ndim} b :{b.ndim} c :{c.ndim} d :{d.ndim}')

In [ ]:
f = np.array([[[1,2,3],[1,3,5]],[[2,3,4],[5,6,7]]])
f.ndim

In [ ]:
f

In [ ]:
arr = np.array([1,2,3,4],ndmin = 5)
arr

In [ ]:
arr.ndim

## ACCESSING ARRAY

In [ ]:
q = np.array([1,45,'ds','da'])
q[3]

In [ ]:
q[3]+q[2]

In [ ]:
w = np.array([[1,2,3,4,5],[5,6,7,8,9]])
w

In [ ]:
w[1,2]

In [ ]:
w[0,1]

In [ ]:
r = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
r.ndim

In [ ]:
r

In [ ]:
r[0,1,2]

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

In [ ]:
a[-1,-2]

## NUMPY SLICING

In [ ]:
a = np.array([12,3,4,5,6])
a[:4]

In [ ]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

In [ ]:
b[:,1:]

In [ ]:
c = np.array([[[1,2,3],[4,5,6]],[[45,56,67],[67,78,89]]])
c

In [ ]:
c[0,:,0:2]

## DATA TYPE OF AN ARRAY

In [ ]:
arr = np.array([1,2,3])
brr = np.array([1,2,'ds'])
crr = np.array(['ds','da','de'])
print(arr.dtype,brr.dtype,crr.dtype)

In [ ]:
a = np.array([1,2,3],dtype = 'U') # S,f,U
a.dtype

In [ ]:
# a = np.array(['a',2,3],dtype = 'i')
# a.dtype

In [ ]:
a = np.array([1.1,2.2,3.3])
b = a.astype(int)
b

In [ ]:
b.dtype

In [ ]:
s = np.array([0,1,3])
r = s.astype(bool)
r

In [ ]:
r.dtype

## COPY VS VIEW

In [ ]:
a = np.array([1,2,3,4])
b = a.copy()
print(f'a:{a} \n b:{b}')

In [ ]:
a[0] = 100
print(f'a:{a} \n b:{b}')

In [ ]:
d = np.array([1,2,3,4])
f = d.view()
print(f'd:{d} \n f:{f}')

In [ ]:
d[1] = 23

In [ ]:
print(f'd:{d} \n f:{f}')

## SHAPE

**The output tuple represent the number of element in that particular dimension**

In [ ]:
a = np.array(43)
a.shape

In [ ]:
b = np.array([1,2,3],ndmin = 5)
b.shape

In [ ]:
c = np.array([[1,2,3],[2,3,4]])
c.shape

In [ ]:
d = np.array([[[1,2,3],[2,3,4]]])
d.shape

In [ ]:
d = np.array([[[[1,2,3],[2,3,4]]]])
d.shape

In [ ]:
d = np.array([[[[1,2,22,3,4]]]])
d.shape

In [ ]:
b = np.array([1,2,3])
b.shape

## RESHAPING

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [ ]:
b = a.reshape(4,3)
b

In [ ]:
c = a.reshape(2,3,2)
c

In [ ]:
b = np.array([1,2,3,4,5,6,7,8])
c = b.reshape(2,2,2)
c

In [ ]:
e = b.reshape(-1,2)
e

In [ ]:
arr = np.array([[1,2,3],[3,4,5]])
arr.reshape(-1)

## JOINS

## ARRAY ITERATION

In [ ]:
a = np.array([[1,2,3],[3,4,5]])
for i in a:
    print(i)

In [ ]:
for i in a:
    for j in i:
        print(j)

In [ ]:
for i in np.nditer(a):
    print(i)

In [ ]:
b = np.array([[[[1,2,3,4],[2,3,4,5]],[[2,3,4,7],[6,7,8,9]]]])
for i in np.nditer(b):
    print(i)

In [ ]:
for i,x in np.ndenumerate(b):
    print(i,x)

In [18]:
a1 = np.array([1,2,3])
a2 = np.array([3,4,5])
np.concatenate((a2,a1))

array([3, 4, 5, 1, 2, 3])

In [20]:
a1 = np.array([[1,2,3],[2,3,4]])
a2 = np.array([[3,4,5],[6,7,8]])
np.concatenate((a2,a1),axis = 1)

array([[3, 4, 5, 1, 2, 3],
       [6, 7, 8, 2, 3, 4]])

In [7]:
np.concatenate((a1,a2))

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
a1 = np.array([1,2,3])
a2 = np.array([3,4,5])
np.stack((a1,a2),axis = 1)

array([[1, 3],
       [2, 4],
       [3, 5]])

In [15]:
np.hstack((a1,a2))

array([1, 2, 3, 3, 4, 5])

In [16]:
np.vstack((a1,a2))

array([[1, 2, 3],
       [3, 4, 5]])

In [17]:
np.dstack((a1,a2))

array([[[1, 3],
        [2, 4],
        [3, 5]]])

## SPLITTING

In [27]:
arr = np.array([1,2,3,4,5,6,7,8])
np.array_split(arr,2)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [29]:
c = np.array_split(arr,5)

In [30]:
c[2]

array([5, 6])

In [31]:
c[3]

array([7])

In [35]:
b = np.array([[1,2,3,4],[2,3,4,5],[1,2,7,8]])
np.array_split(b,3)

[array([[1, 2, 3, 4]]), array([[2, 3, 4, 5]]), array([[1, 2, 7, 8]])]

In [36]:
c = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
np.array_split(c,3)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [38]:
c = np.array([[1, 2,3], [1,3, 4], [4, 5, 6], [9, 7, 8], [0, 9, 10], [0, 11, 12]])
np.array_split(c,3,axis = 1)

[array([[1],
        [1],
        [4],
        [9],
        [0],
        [0]]),
 array([[ 2],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]),
 array([[ 3],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]])]

## SEARCHING

In [39]:
a = np.array([1,2,3,4,5,'ajeeth'])
np.where(a == 'ajeeth')

(array([5], dtype=int64),)

In [2]:
c = np.array([1,2,3,4,5,6,7,8])
np.where(c%2 == 0)

(array([1, 3, 5, 7], dtype=int64),)

In [41]:
np.where(c%2 == 1)

(array([0, 2, 4, 6], dtype=int64),)

In [3]:
np.where(c>4,'High','Low')

array(['Low', 'Low', 'Low', 'Low', 'High', 'High', 'High', 'High'],
      dtype='<U4')

In [5]:
np.argwhere(c>4) # Returns the index position

array([[4],
       [5],
       [6],
       [7]], dtype=int64)

In [45]:
b = np.array([2,3,4,1,8,9])
np.searchsorted(b,7)

4

In [46]:
x = np.searchsorted(b,7,side = 'right')
x

4

In [48]:
v = np.array([1,3,5,7])
np.searchsorted(v,[2,4,6])

array([1, 2, 3], dtype=int64)

## SORT

In [50]:
r = np.array([3,2,0,1]) # try alphabets
np.sort(r)

array([0, 1, 2, 3])

In [51]:
c = np.array([True,False,True,False])
np.sort(c)

array([False, False,  True,  True])

In [52]:
c = np.array([[3,7,1],[5,0,0]])
np.sort(c)

array([[1, 3, 7],
       [0, 0, 5]])

## FILTERING

In [2]:
a = np.array([42,34,56,71,90])
x = [True,False,True,False,True]
a[x]

array([42, 56, 90])

In [3]:
filter_array = []
for i in a:
    if i > 50:
        filter_array.append(True)
    else:
        filter_array.append(False)

n = a[filter_array]

In [4]:
n

array([56, 71, 90])

In [5]:
filter_array = []
for i in a:
    if i%2 == 0:
        filter_array.append(True)
    else:
        filter_array.append(False)

b = a[filter_array]

In [6]:
b

array([42, 34, 56, 90])

In [7]:
l = a > 42
a[l]

array([56, 71, 90])

In [8]:
j = a%2 == 0
a[j]

array([42, 34, 56, 90])