# RANDOM

In [1]:
import numpy.random as rd
import numpy as np

## RANDINT

In [14]:
 # rd.randint()

In [3]:
a = rd.randint(100)
a

96

In [4]:
a = rd.randint(100,size = 100)
a

array([51, 57, 11, 41, 38, 75, 46,  7, 92, 56,  0, 33, 99,  1, 12, 37, 56,
        7, 92, 48, 63, 86,  9, 64, 58, 71, 39, 83, 38, 14, 36, 43, 23, 23,
       75, 60, 76, 12, 56, 54, 93,  1, 46, 91, 28, 35, 37, 47, 59, 56, 40,
       62, 62,  3, 34, 25, 71, 65, 38, 15,  2, 32, 92, 44, 14, 63, 81, 63,
       53, 63, 46, 29, 33, 72, 28, 11, 28, 74, 45, 93, 51, 34, 37, 38, 47,
       73, 74, 99, 93, 68, 29, 89, 28, 39, 37, 85, 13, 30, 17, 66])

In [5]:
rd.randint(100,size = (3,5))

array([[94, 34, 38, 75, 98],
       [38, 81,  9, 92, 51],
       [20, 40, 26, 77, 34]])

In [6]:
rd.randint(100,size = (2,2,4))

array([[[ 3, 39, 85, 77],
        [84, 81, 47,  7]],

       [[13, 18, 49, 86],
        [90,  2, 61,  9]]])

## RAND

In [7]:
rd.rand()

0.802474122364455

In [8]:
rd.rand(5)

array([0.85543604, 0.03973772, 0.30618401, 0.32690524, 0.0868912 ])

In [9]:
rd.rand(10,2)

array([[0.26043032, 0.96021801],
       [0.34605433, 0.50311513],
       [0.88468741, 0.7143698 ],
       [0.23487734, 0.26131974],
       [0.29852052, 0.86474755],
       [0.16739198, 0.36465277],
       [0.65075051, 0.81162522],
       [0.06254435, 0.77863884],
       [0.28737108, 0.40064539],
       [0.78429713, 0.87758209]])

## CHOICE

In [10]:
x = rd.choice([2,3,4,1])
x

2

In [11]:
x = rd.choice([2,3,4,1],size = 10)
x

array([1, 1, 1, 3, 3, 1, 3, 1, 3, 1])

In [12]:
x = rd.choice([2,3,4,1],size = (2,5))
x

array([[4, 3, 4, 4, 3],
       [3, 2, 4, 2, 4]])

# UFUNCS

**UNIVERSAL FUNCTIONS ARE NUMPY FUNCTION THAT ARE USED TO OPERATE *ndarray* OBJECTS**  
**UFUNCS ARE USED TO IMPLEMENT VECTORIZATION (A FASTER WAY TO ITERATE OVER ELEMENTS)**  
**CONVERTING ITERATIVE STATEMENTS INTO VECTOR BASED OPERATION IS CALLED VECTORIZATION**

In [15]:
x = [1,2,3,4]
y = [5,6,7,8]
z = []
for i,j in zip(x,y):
    z.append(i+j)
z

[6, 8, 10, 12]

In [18]:
np.add(x,y)

array([ 6,  8, 10, 12])

## CREATING OWN NUMPY UFUNC

In [31]:
def mymul(a,b):
    return a*b

In [32]:
def square(z):
    return z*z

In [33]:
vfunc = np.vectorize(square)

In [34]:
vfunc(2)

array(4)

In [20]:
m = np.frompyfunc(mymul,2,1)
m([1,2,3],[4,5,6])

array([4, 10, 18], dtype=object)

In [21]:
type(m)

numpy.ufunc

In [23]:
type(np.add)

numpy.ufunc

## SIMPLE ARITHEMETIC

In [24]:
a = np.array([10,20,30,30,50,60])
b = np.array([2,4,6,8,10,12])

In [25]:
np.add(a,b)

array([12, 24, 36, 38, 60, 72])

In [26]:
np.subtract(a,b)

array([ 8, 16, 24, 22, 40, 48])

In [27]:
np.multiply(a,b)

array([ 20,  80, 180, 240, 500, 720])

In [28]:
np.divide(a,b)

array([5.  , 5.  , 5.  , 3.75, 5.  , 5.  ])

In [30]:
x = np.array([2,3,4,5])
y = np.array([1,2,3,4])

In [31]:
np.power(x,y)

array([  2,   9,  64, 625])

In [32]:
np.mod(a,b)

array([0, 0, 0, 6, 0, 0])

In [33]:
np.remainder(a,b)

array([0, 0, 0, 6, 0, 0])

In [34]:
np.divmod(a,b)

(array([5, 5, 5, 3, 5, 5]), array([0, 0, 0, 6, 0, 0]))

In [36]:
c = np.array([-1,2,-3,-2,0])
np.absolute(c)

array([1, 2, 3, 2, 0])

## ROUNDING DECIMALS

### TRUNCATION

In [37]:
np.trunc([-3.1666,3.6667])

array([-3.,  3.])

In [38]:
np.fix([-3.1666,3.6667])

array([-3.,  3.])

### ROUNDING

In [39]:
np.around(3.16666,3)

3.167

### FLOOR

In [40]:
np.floor([-.166,3.454566])

array([-1.,  3.])

### CEIL

In [41]:
np.ceil([-.166,3.454566])

array([-0.,  4.])

## LOGS

In [43]:
a = np.arange(1,10)

In [46]:
np.log2(a)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [47]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [48]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [49]:
from math import log
nplog = np.frompyfunc(log,2,1)
nplog(100,15)

1.7005483074552052

## SUMMATION

In [50]:
a = np.array([1,2,3])
b = np.array([2,3,4])

In [51]:
np.add(a,b)

array([3, 5, 7])

In [53]:
np.sum([a,b])

15

In [54]:
np.sum([a,b],axis = 1)

array([6, 9])

In [55]:
np.cumsum(a)

array([1, 3, 6])

## PRODUCTS

In [56]:
a = np.array([1,2,3,4])
np.prod(a)

24

In [59]:
b = np.array([2,3,4,2])
np.prod([a,b])

1152

In [60]:
np.prod([a,b],axis = 1)

array([24, 48])

In [61]:
np.cumprod(b)

array([ 2,  6, 24, 48])

## TRANSPOSE

In [3]:
a = np.array([[1,2,3]])
a.transpose()

array([[1],
       [2],
       [3]])

In [4]:
b = np.array([[1,2,3],[5,6,7]])
b

array([[1, 2, 3],
       [5, 6, 7]])

In [5]:
b.transpose()

array([[1, 5],
       [2, 6],
       [3, 7]])

In [6]:
b.T

array([[1, 5],
       [2, 6],
       [3, 7]])

## AGGREGATE FUNCTION

In [7]:
a = np.array([1,3,6,7,8])

In [8]:
np.sum(a)

25

In [9]:
np.mean(a)

5.0

In [10]:
np.median(a)

6.0

In [11]:
np.max(a)

8

In [12]:
np.min(a)

1

In [13]:
np.std(a)

2.6076809620810595

In [14]:
np.var(a)

6.8

In [17]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.sum(matrix,axis = 1)

array([ 6, 15, 24])

In [23]:
np.sum(matrix,axis = 0)

array([12, 15, 18])

## LOGICALS

In [24]:
c= np.array([2,5,7,3,8,1])
np.logical_and(c>3 ,c<8)

array([False,  True,  True, False, False, False])

In [25]:
np.logical_or(c==1,c==6)

array([False, False, False, False, False,  True])

In [26]:
logic = np.logical_or(c==1,c==6)
c[logic]

array([1])

In [27]:
a = np.array([2,0,2,0,4,0])
np.nonzero(a)

(array([0, 2, 4], dtype=int64),)

## MISSING VALUES

In [36]:
np.nan # not a number

nan

In [39]:
a = np.array([1,2,3,np.nan,5,6])

In [38]:
a

array([ 1.,  2.,  3., nan,  5.,  6.])

In [42]:
a = np.array([1,2,3,np.nan,5,-np.inf,6,np.inf])

In [43]:
a

array([  1.,   2.,   3.,  nan,   5., -inf,   6.,  inf])

In [44]:
np.isnan(a)

array([False, False, False,  True, False, False, False, False])

In [45]:
np.isinf(a)

array([False, False, False, False, False,  True, False,  True])

In [46]:
np.isfinite(a)

array([ True,  True,  True, False,  True, False,  True, False])